### ISSUE TITLE
Allow to build custom_data sample data

### ISSUE THREAD

**Issue by pdany1116** [appsignal/appsignal-ruby#1012]
Hello, my use case is that I want to set some default custom_data for all requests, but if let's say I want to add more custom data throughout the request I have no easy way to do this.

For example, the default data might look like this:
```ruby
Appsignal::Transaction.current.set_sample_data('custom_data', { current_context: { user_id: 42 } })
```
but if later I want to add some additional custom data I would have recreate the default data because it is overwritten:
```ruby
def foo(input)
  ... # code that raises an error
rescue StandardError => error
  Appsignal::Transaction.current.set_error(error)
  Appsignal::Transaction.current.set_sample_data('custom_data', { current_context: { user_id: 42 }, params: input })
end
```

It would be nice to have a way to add data to custom_data instead of replacing it. What do you think?

**Comment by unflxw** [comment]
Hi @pdany1116! For the use case where you're adding single primitive values one at a time, you might find the tags more useful, as they do work cumulatively:

```
Appsignal.tag_request(:user_id => 42)
Appsignal.tag_request(:is_admin => false)
``` 

Generally, we try not to make too many assumptions about what the structure of the user-provided custom data is. But since calling `set_sample_data` more than once is fine, you can implement this yourself as a monkey-patch on the `Appsignal::Transaction` class:

```ruby
class Appsignal::Transaction
  def add_custom_data(key, value)
    @custom_data ||= {}
    @custom_data[key] = value
    set_sample_data('custom_data', @custom_data)
  end
end

Appsignal::Transaction.current.add_custom_data(:current_context, {:user_id => 42})
Appsignal::Transaction.current.add_custom_data(:params, input)
```

I hope this helps! I'm closing this issue, but do feel free to re-open (or reach out at support@appsignal.com) is this does not work for you.

**Comment by pdany1116** [comment]
Thanks @unflxw for the answer! Tags are great, I already use them for some additional info. The monkey-patch should do the trick, thank you!
