### ISSUE TITLE
Set the environment for deploy reporting in Capistrano

### ISSUE THREAD

**Issue by adamof** [appsignal/appsignal-ruby#118]
Hey guys,

I noticed that there was a bit of discussion about this in #94, but I am having some issues with this with our current setup.

#### Setup
We have several capistrano stages, deploying the same rails_environment, example:
- Rails environment - `staging`
- We have two capistrano stages - `staging` and `beta`
- AppSignal is active for the `staging` env

#### The problem
When we deploy `staging` stage, the deploys are reported, but this is not true when we deploy the `beta` stage (since there is no appsignal config specified for the beta environment). If I just add the environment in the appsignal.yml, then another environment is created on AppSignal containing just the deploys.

#### Solution?
Would it be possible to somehow set the environment which AppSignal checks when deciding wether or not to report the deploy?

**Comment by tombruijn** [comment]
Hi @adamof, if I understand the issue correctly you're using multiple capistrano stages (`staging` and `beta`), but no different `staging` and `beta` Rails environments.

You do want to track the `beta` stage, which runs in the rails environment `staging`. However, since we listen to the `beta` capistrano stage you don't get a deploy notification on for `beta` deploys.

What we can do is allow you to set a specific `appsignal_env` in capistrano. By default it listens to the capistrano stage, but if these don't match, as in your case, you can override it.

```ruby
# config/deploy/staging.rb
set :stage, :staging
set :rails_env, :staging
# AppSignal env is `:staging`
```

```ruby
# config/deploy/beta.rb
set :stage, :beta
set :rails_env, :staging
set :appsignal_env, :staging
```

I think this would solve your problem?

---

As an aside: In your setup it does mean everything from both stages (`staging` and `beta`) are collected under the `staging` environment in AppSignal, which might clutter it a bit and you might not immediately be able to see what error comes from which stage.

**Comment by adamof** [comment]
Hey @tombruijn thanks for the response! I think this solution would work great for us. 
As far as the mixed environments go, this is not much of an issue for us at the minute.

**Comment by tombruijn** [comment]
@adamof I made a PR for this change in PR #119

You can try it out by adding this to your Gemfile:

```ruby
# Gemfile
gem 'appsignal', git: 'git@github.com:appsignal/appsignal-ruby.git', branch: 'capistrano_appsignal_env'
```

Let me know if this is the behavior you want.

**Comment by adamof** [comment]
Yep, that work! 🎆

**Comment by tombruijn** [comment]
Great to hear!

I'll get the PR reviewed, merged and released. Will update you once we release a new official gem version you can use directly.

**Comment by adamof** [comment]
![](https://media.giphy.com/media/k39w535jFPYrK/giphy.gif)

**Comment by tombruijn** [comment]
The PR was merged.
I'll keep you up-to-date on a new gem release
