### ISSUE TITLE
Would like to be able to control what we use AppSignal for

### ISSUE THREAD

**Issue by ixti** [appsignal/appsignal-ruby#12]
Heya,

I would like to be able to disable _any_ Exception logging to AppSignal.
As well as I want to be able completely disable tracking of background jobs.

**Comment by oshanz** [comment]
I'm also looking for this. just want to disable performance metrics for some internal apps.

**Comment by roytomeij** [comment]
Hi @oshanz! Our position on this hasn't changed over the years, specially since we've added many features (e.g. Anomaly Detection) that rely on accurate statistics. While I understand the desire to limit use of AppSignal to exceptions only, we're not an exception tracker and strongly believe in painting the complete picture by providing a consolidated approach.

**Comment by snkashis** [comment]
@ixti did you ever fork/make public your monkeypatched version that supports what you were asking for here? I want to disable exception tracking completely and coexist with bugsnag.

**Comment by ixti** [comment]
@snkashis Heya, sorry, that was very long ago, but as far as I remember we've abandoned idea of using AppSignal, and APM in general, and focused on bugs using Rollbar only :D
