### ISSUE TITLE
Support Puma lowlevel_error_handler

### ISSUE THREAD

**Issue by tmaier** [appsignal/appsignal-ruby#1247]
You have a puma plugin. This is really great.

https://puma.io/puma/index.html#error-handling

It would be great, if the plugin would register directly a `lowlevel_error_handler`.
Or alternatively, if you could document its usage at https://docs.appsignal.com/ruby/integrations/puma.html

Considerations/learnings from others:

- https://github.com/puma/puma/discussions/3135

**Comment by tombruijn** [comment]
Thanks for the suggestion!
I hope it's not raised in the main Puma process because AppSignal is not active there, but if it's called in workers, we could maybe report it. It depends a bit on what kind of errors it tracks because we have gotten some reports recently of web server errors that we already report that a bunch of people don't want to track by default.

**Comment by tmaier** [comment]
Thank you guys!
