### ISSUE TITLE
Error in Custom instrumentation for background jobs

### ISSUE THREAD

**Issue by blackchestnut** [appsignal/appsignal-ruby#230]
Hi,
I have error 
```
NoMethodError: undefined method `env' for #<Hash:0x0056061a487d00>
from /home/apps/complead/production/shared/bundle/ruby/2.3.0/gems/appsignal-2.0.4/lib/appsignal/transaction.rb:287:in `sanitized_environment'
```
 for example:
http://docs.appsignal.com/ruby/instrumentation/background-jobs.html#start-a-transaction
```ruby
transaction = Appsignal::Transaction.create(
  SecureRandom.uuid,
  Appsignal::Transaction::BACKGROUND_JOB,
  {} # or ENV.to_hash
)
#...
```
The third argument is a `request`
https://github.com/appsignal/appsignal-ruby/blob/v2.0.4/lib/appsignal/transaction.rb#L23
and then on the line 287 raise an error:
```ruby
def sanitized_environment
  return unless request.env
  #...
```
https://github.com/appsignal/appsignal-ruby/blob/v2.0.4/lib/appsignal/transaction.rb#L287

Perhaps somewhere I made a mistake in setting up :(

P.S. For temporary hotfix replaced on:
```ruby
transaction = Appsignal::Transaction.create(
  SecureRandom.uuid,
  Appsignal::Transaction::BACKGROUND_JOB,
  OpenStruct.new # <---
)
#...
```

**Comment by tombruijn** [comment]
Thanks for the report @blackchestnut !

I'll have a look at what's going wrong there. I see that documentation page could also use a few updates. Will keep you updated

**Comment by tombruijn** [comment]
Looks like this is a bug. I've updated the docs page to use the `Appsignal::Transaction::GenericRequest` class to wrap the env. http://docs.appsignal.com/ruby/instrumentation/background-jobs.html

Instead of your workaround I recommend you use a `Appsignal::Transaction::GenericRequest` object.

I will create a PR so this would at least not crash when you supply a hash or another type of object.
