### ISSUE TITLE
What does enable_minutely_probes do?

### ISSUE THREAD

**Issue by andrew** [appsignal/appsignal-ruby#268]
Just setting up appsignal on https://github.com/librariesio/libraries.io and noticed that there's an option in the ruby gem called `enable_minutely_probes` which isn't documented in http://docs.appsignal.com/ruby/configuration/options.html

What does it do? Should I enabled it or ignore it?

Thanks!

**Comment by tombruijn** [comment]
Hi @andrew!

Sorry for the belated response. This issue came in a bit under the radar 😓 

The minutely probes are currently only used by the AppSignal GC profiler probe. We have one minutely probe to track metrics from the Ruby Garbage Collector. This data is currently unused while we work on a way to display this properly in the AppSignal.com UI. We don't have a release date for this feature yet.

Since this feature was not shipped in its entirety so far, we have not documented it on docs.appsignal.com.

You can ignore the `enable_minutely_probes` option. It's **not** on by default.

Sorry for the confusion!

**Comment by andrew** [comment]
No problem, thanks for the response, I was wondering why I couldn't find any GC data in the UI, that makes sense now!
