### ISSUE TITLE
`log: stdout` does not work

### ISSUE THREAD

**Issue by tonytonyjan** [appsignal/appsignal-ruby#318]
appsignal version: 2.2.1
ruby version: 2.4.1
rails version: 5.1.1

Reproduce:

1. Create a new rails app with `rails new`
2. Add the gem to `Gemfile`

       gem 'appsignal', '2.2.1'

2. `bundle install`
3. `bundle exec appsignal install xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`
4. update config/appsignal.yml 

       default: &defaults
         push_api_key: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
         name: "Hello"
         log: stdout
       development:
         <<: *defaults
         active: true
       production:
         <<: *defaults
         active: true

4. `bin/rails s`
5. `cat log/appsignal.log`

**Comment by tombruijn** [comment]
Hi @tonytonyjan,

This behavior is correct, although a bit confusing.

If I'm correct you should only see logs from our system agent in the log file? Prefix `(agent)` in the log file. The logs from the `(process)` and `(extension)` should show up in your application's STDOUT.

---

## What's happening when you set `log: stdout`?

On the [`:log`](https://docs.appsignal.com/ruby/configuration/options.html#appsignal_log-log) documentation page you can see we've added a note about `log: "stdout"` not applying to our system agent.

The Ruby application will log to STDOUT when `log: stdout` is set. This means our Ruby gem and C-extension will log to the parent's application STDOUT.

Our separate system agent however, doesn't log to STDOUT. Regardless of the `:log` setting it will always try to log to the `appsignal.log` file, either in `log/appsignal.log` or `/tmp/appsignal.log`. This is because our agent is a completely separate process and it has no access to the Ruby application's STDOUT pipe. 

In issue #184 (where I see you also left a comment) we added the `log: stdout` feature, with the exception for the agent, see the strikethrough list item. I wrote an RFC to add support for this, but the overall changes were too big for us to work on this anytime soon. For now we've put any work on this on hold and are even considering other solutions to somehow make the agent logs available elsewhere.

(I see the terminology is a bit outdated from what we're using now. I'm going to update that.)

---

I hope the above explains why our agent still creates a log file even if the config is set to `stdout`. Let me know if this the problem you're seeing, and if not, what the contents of your log file are. If you want to not send (potentially) sensitive data in your logs over GitHub, feel free to reach out on support@appsignal.com
