### ISSUE TITLE
NameError: uninitialized constant AppSignalController::AppSignal

### ISSUE THREAD

**Issue by Schwad** [appsignal/appsignal-ruby#320]
## VERSIONS

Rails: 5.0.3
Ruby: 2.3.3p222

## ISSUE

We have AppSignal integrated in our application and have been loving the experience. Recently the need came up to manually raise some errors. I was going to build in an in-house POST request to a slack channel, but would really rather keep all of our exceptions wrapped up in AppSignal for documentation purposes. 

I'm coming across an error, which I really hope is from me being braindead this morning. 

Following the docs I ran `AppSignal.set_error(error)` in a controller and received this stacktrace: 

```
[13] pry(#<AppSignalController>)> AppSignal.set_error(params[:backtrace])
NameError: uninitialized constant AppSignalController::AppSignal
from (pry):14:in `catch_error'
```

Thoughts?

**Comment by tombruijn** [comment]
Hi @Schwad,

Great to see you're loving the experience! 

The problem here is that our module name is called `Appsignal` without the capital `S`. Otherwise our gem should officially be called `app_signal`.

What happens is that when calling `AppSignal.set_error` Ruby can't find a module with that name anywhere and thus errors our saying it can't find it in the scope you called it in.

`Appsignal.set_error` should do the trick.

Did you find that exact capitalization example in our docs somewhere?

**Comment by Schwad** [comment]
Man, I must have been having a long day. 

You're correct in that that resolved my error.... 

Hopefully if some other tired soul gets the same error some day this issue will give them a heads up to double check their capitalization! Thanks so much!

**Comment by tombruijn** [comment]
Thanks for trying to stay true to the correct capitalizing the brand name 👍  We appreciate it

I have wondered if aliasing an `AppSignal` constant to the `Appsignal` module would be a nice  addition to the gem. It would have certainly prevented your issue. And allow users to use the correct capitalization of the brand name 😄
