### ISSUE TITLE
Getting "Too many open files" error on hooks

### ISSUE THREAD

**Issue by fredbaa** [appsignal/appsignal-ruby#390]
Using version 1.2.3

getting a lot of these errors in our production server:

>  Too many open files - getaddrinfo
>   appsignal (1.2.3) lib/appsignal/hooks/redis.rb:18:in `block in process'

This is for redis. We're also getting error on hooks/net_http.rb:
>  lib/appsignal/hooks/net_http.rb:24:in `block in request'

What could possibly cause this error and how to avoid it?

**Comment by jeffkreeftmeijer** [comment]
Hey @fredbaa! 👋

Thanks for letting us know about this. It looks like AppSignal is in the stack trace because we’re wrapping the calls from both libraries. On version 1.2.3, the lines from your backtraces point to where we do that for both [Redis](https://github.com/appsignal/appsignal-ruby/blob/v1.2.3/lib/appsignal/hooks/redis.rb#L18) and [Net::HTTP](https://github.com/appsignal/appsignal-ruby/blob/v1.2.3/lib/appsignal/hooks/net_http.rb#L24). This would mean the errors aren't actually caused by AppSignal, but the exception travels through the AppSignal blocks on its way up the stack. Could that be the case?

In your stack traces, you should have lines before the AppSignal ones, which will show you where the error came from instead. Could you check that and let us know what you find?

Also, as a sidenote; we released a lot of improvements to the AppSignal integration since 1.2.3 (we’re on 2.5.1 now). You should be able to upgrade without updating your setup or configuration, so you should be able  to run `bundle update appsignal` to upgrade to the new version. Also, please let us know if you run into any issues. :)
