### ISSUE TITLE
SidekiqProbe is not configured correctly for hostname

### ISSUE THREAD

**Issue by timdiggins** [appsignal/appsignal-ruby#658]
## Describe the bug

Given I have configured a Hostname using config yml (`hostname`) or environment variable (`APPSIGNAL_HOSTNAME`) 
When I'm looking at the sidekiq dashboard and I look at the queues hosts
The queue hosts use their own autodetected hostname (socket hostname or ip address) rather than the configured hostname

- Using AppSignal for Ruby gem version 2.11.0

## Fix

The problem is that SidekiqProbe defines an optional config parameter for new (`Appsignal::Probes::SidekiqProbe#initialize`), but it is instantiated without parameters by `Appsignal::Minutely.initialize_probe`. The test for this in sidekiq_spec.rb is radically different for the (correct) test in puma_spec.rb and makes use of the (I believe) otherwise unused config parameter).

I think this could be fixed by making the test for sidekiq_spec the same as puma_spec and then likewise the implementation?

I'm blocked on this by #657

**Comment by tombruijn** [comment]
Hi @timdiggins,

We offer the hostname option in the Sidekiq probe, because it tries to get the hostname from Sidekiq/redis first. The `hostname` option for the probe is there to override this when you don't want the auto detect behavior there.
https://github.com/appsignal/appsignal-ruby/blob/096d2858e3aa6e89a786c0416b1210f668faf413/lib/appsignal/probes/sidekiq.rb#L87-L101

You can do that as described here: https://docs.appsignal.com/ruby/integrations/sidekiq.html#minutely-probe-configuration
It will overwrite the previously auto initialized sidekiq probe.

```ruby
# config/initializers/appsignal.rb or a file that's loaded on boot
Appsignal::Minutely.probes.register(
  :sidekiq, # Use the same key as the default Sidekiq probe to override it
  Appsignal::Probes::SidekiqProbe.new(:hostname => "my_sidekiq_hostname")
)
```

Does that help?

**Comment by timdiggins** [comment]
Yes, thanks I can use that code as a workaround in our local case, but from a code point of view, is there a strong reason not to configure the SidekiqProbe the same as PumaProbe, and indeed the rest of appsignal ruby?

I'd expect them to be parallel, and we were recommended by Appsignal support to configure the hostname/APPSIGNAL_HOSTNAME in order to override the automatic hostnames in the sidekiq dashboard (unless we misunderstood the recommendations)

But if there is a strong reason for a break in parallelism, I think it should be heavily signposted in the docs (and/or code).

**Comment by tombruijn** [comment]
We chose not to use the app's hostname (as configured in AppSignal) but rather the sidekiq redis hostname so that it wouldn't report queues for all app hosts. In the scenario that 5 hosts talk to 1 redis server that has the shared sidekiq queue. Otherwise we'd report for 5 hosts the same metrics under different hostnames. This could create the impression 5 times as much jobs are being processed.

**Comment by timdiggins** [comment]
Ah - interesting. I had been thinking (from the perspective of a containerized, orchestrated system like Heroku, but using Kubernetes and other systems would be similar, where the "hosts" may be multiple but the actual host name is non-meaningful, and the only interesting thing is the aggregate) that the point of the hostname / APPSIGNAL_HOSTNAME  was to integrate multiple distinct hosts as one entity (so that this ENV variable / config is unlikely to vary from server to server, but actually be the same on every distinct container for the same environment).

Whereas the model you are talking about with SidekiqProbe is looking at each "host" as a distinct entity in its own right with separate hostnames (determined by config or distinct environment variables). 

Does this mean that given the configuration as discussed (`Appsignal::Minutely.probes.register(:sidekiq,  Appsignal::Probes::SidekiqProbe.new(:hostname => "my_sidekiq_hostname"))`), if I do this configuration with multiple sidekiq hosts (dynos in Heroku), I will have the problem of there being (apparently) an incorrect (multiplied) number in the queue for sidekiq? In which case, it's probably not a good idea and we better stick with the default hostnames. (though it's still quite weird because you get multiple reports of queues - one trace per sidekiq dyno, which seemed odd to me before).

**Comment by tombruijn** [comment]
Having multiple distinct hosts report under the same hostname could cause issues. The gauge metrics would overwrite each other, if one host reports a "user_count" of 100 and another host would report 200, the last received value for that minute is stored, not a sum or average.

For counter and distribution/measurements this would work because the metrics get counted onto one another.

Metric type docs: https://docs.appsignal.com/metrics/custom.html#metric-types

The sidekiq probe only reports gauges, so multiple distinct hosts with the same name fetching metrics from a shared redis database on another host probably would be fine. The heroku dyno example with an external redis database.

But when the redis database would run on the same system as sidekiq and the redis queues have different values, it would report different values per host under the same hostname, causing issues with gauge metrics being overwritten.

> Does this mean that given the configuration as discussed (Appsignal::Minutely.probes.register(:sidekiq, Appsignal::Probes::SidekiqProbe.new(:hostname => "my_sidekiq_hostname"))), if I do this configuration with multiple sidekiq hosts (dynos in Heroku), I will have the problem of there being (apparently) an incorrect (multiplied) number in the queue for sidekiq?

By default, the sidekiq probe should automatically choose the redis server hostname in this case, which is the same for all dynos, and report it under that redis server host name.

If all your Sidekiq probe is set per dyno to the same hostname, that should still report the same values the same way, just not using the automatically detected redis server hostname, for example `my_sidekiq_hostname`: `Appsignal::Minutely.probes.register(:sidekiq, Appsignal::Probes::SidekiqProbe.new(:hostname => "my_sidekiq_hostname"))`

The problem with duplicate metrics being reported arises when the hostname is dynamic but the actual redis server is not, for example `my_sidekiq_hostname_x`: `Appsignal::Minutely.probes.register(:sidekiq, Appsignal::Probes::SidekiqProbe.new(:hostname => "my_sidekiq_hostname_#{ENV["SOME_KEY"]"))`

> In which case, it's probably not a good idea and we better stick with the default hostnames. (though it's still quite weird because you get multiple reports of queues - one trace per sidekiq dyno, which seemed odd to me before).

How is being reported now for you? We can also have a look at this together if you send us a message at support@appsignal.com
