### ISSUE TITLE
Version 2.11.10 missing in CHANGELOG and codebase

### ISSUE THREAD

**Issue by sbocinec** [appsignal/appsignal-ruby#830]
## Describe the bug

The latest `v2` version of the `appsignal-ruby` gem is missing in the [`CHANGELOG.md`](https://github.com/appsignal/appsignal-ruby/blob/main/CHANGELOG.md):

* the `2.11.10` gem is published to rubygems.org, also the `v2.11.10` tag exists https://github.com/appsignal/appsignal-ruby/tree/v2.11.10 in the source code. I wonder if it accidentaly dropped out during merge/rebase with `v3` (that arrived around the same time)?
* briefly checking the git log for the `main` branch it appears the commits between `v2.11.10` and `v2.11.9` are also missing in the commit history.

It would be great though if this latest `v2` version is properly documented in the CHANGELOG. 
Thank you!

## To Reproduce

- Install latest `appsignal-ruby` `v2` gem version
- Assert that `v2.11.10` is installed
- Check [`CHANGELOG.md`](https://github.com/appsignal/appsignal-ruby/blob/main/CHANGELOG.md) for the changes
- There is no mention of this version

**Comment by tombruijn** [comment]
Hi @sbocinec,

The 2.11.10 release was a backport of a fix in PR #720 previously added to version 3.0.3: https://github.com/appsignal/appsignal-ruby/blob/main/CHANGELOG.md#303

You can find 2.11.0 in the `2.11-stable` branch: https://github.com/appsignal/appsignal-ruby/blob/2.11-stable/CHANGELOG.md

This 2.11.10 release branches off the old 2.x release and is its own thing. The fix of 2.11.0 is also present in 3.0.3, but we not will merge the 2.11.0 branch back into the main branch. This is intentional.

I've added the version entry in commit https://github.com/appsignal/appsignal-ruby/commit/383622facb1c5c6986303dbcc5d9b5b97b2bac51 so it's at least visible in the main changelog now.

**Comment by sbocinec** [comment]
@tombruijn I was confused as the prior versions were part of the CHANGELOG. I now see. Thanks for the detailed clarification and all the great work on AppSignal!
