### ISSUE TITLE
Ruby 3.2+ GVL instrumentation

### ISSUE THREAD

**Issue by bdewater-thatch** [appsignal/appsignal-ruby#918]
Ruby 3.2 gained the ability to instrument Ruby's Global VM Lock with a C extension. This can be useful in determining whether the thread count for Puma or Sidekiq is appropriately configured, see https://bugs.ruby-lang.org/issues/18339 

Example implementation using https://github.com/Shopify/gvltools in Railsbench: https://github.com/casperisfine/railsbench/commit/04a3a7bd1ce7e1aef09687b1f900b38da707f5c1 
Example results on a production app: https://twitter.com/_byroot/status/1620064615907590147 (the thread with Nate Berkopec has some more details on what might be going on)

**Comment by tombruijn** [comment]
Thanks for the tip @bdewater-thatch! We'll have a look at how we can report this.

**Comment by unflxw** [comment]
Did some research on this. Created a [WIP branch with a GVL probe](https://github.com/appsignal/appsignal-ruby/compare/wip-gvltools) and a [WIP test setup](https://github.com/appsignal/test-setups/compare/wip-sinatra-gvltools) for it. It tracks the global timer differential for each minute interval and the waiting threads at a given point in time. Seems to work fine, modulo known issues below.

Open questions:
- Do we want to enable tracking these metrics by default? The WIP branch currently enables both global timer and waiting threads, if the GVLTools gem is installed. From their README:
> The exact overhead is not yet known, early testing showed a 1-5% slowdown on a fully saturated multi-threaded app.
> [On the waiting threads count] It's less precise than timers, but the instrumentation overhead is lower.
- Do we want to add GVLTools as a dependency? The WIP branch currently expects that to be installed by the user.
- The WIP branch adds AppSignal config options that enable the GVLTools metrics when the hook is loaded. But if GVLTools remains an optional dependency, we may want to leave enabling those metrics to the user as well. The current setup allows users to enable and disable those metrics during runtime.
- Do we want to add this metric to a magic dashboard? If so, should we add it to the existing magic dashboard, or to a new one?

Known issues:
- The current implementation of GVLTools tracks nanoseconds in a 32-bit integer. As we collect values every sixty seconds, it overflows fairly quickly, and this behavior can be seen in the WIP test setup. We probably want to call the reset method after we fetch the value, instead of calculating the delta for values between probe calls. We may also want to submit a PR to GVLTools addressing this: the Ruby struct that the thread timings are obtained from tracks seconds and nanoseconds separately, but GVLTools merges the values it obtains into a single nanoseconds counter. It should be possible to keep separate second and nanosecond counters, then merge those into an i64 when sending them to Ruby.

To do:
- [ ] Consider and address open questions
- [ ] Address known issues
- [ ] Add (to) magic dashboard

**Comment by tombruijn** [comment]
@unflxw Did you want to send in an issue to the project to ask these questions you had? That would be good before we continue, so that we have a better idea of how it's supposed to work and if your suggestions you were working on are welcome on the project.

**Comment by unflxw** [comment]
@tombruijn I sent a PR with the overflow fix, and mentioned there that the numbers seemed too high. I'll see if it's addressed there.

**Comment by unflxw** [comment]
The overflow issue was fixed. See if we can push this feature out.

**Comment by unflxw** [comment]
Hi @bdewater-thatch! AppSignal for Ruby 3.3.8 was just released, with support for global VM lock metrics using the `gvltools` library.

If `gvltools` version `0.2.0` or above is installed, AppSignal will automatically report metrics on the global lock timer and waiting threads count.

I hope you find this useful! Please let us know if you have any thoughts or questions.
